SELECT * FROM `siswa` LIMIT 10;
SELECT * FROM `siswa` LIMIT 10, 2;
SELECT * FROM `siswa` LIMIT 0, 2;
SELECT * FROM `siswa` LIMIT 6, 5;
SELECT * FROM `siswa` LIMIT 16, 5;
SELECT * FROM `siswa` LIMIT 2,4;
SELECT * FROM `siswa` WHERE tempat_lahir = 'BANDUNG';
SELECT * FROM `siswa` WHERE jenis_kelamin = 'P';
SELECT * FROM `siswa` WHERE alamat = 'KALIJATI';
SELECT * FROM `siswa` WHERE alamat = 'KALIJATI' AND tempat_lahir = 'SUBANG';
SELECT * FROM `siswa` WHERE nilai >= 78;
SELECT * FROM `siswa` WHERE tempat_lahir != 'SUBANG';
SELECT * FROM `siswa` WHERE tempat_lahir != 'SUBANG' AND nilai >= 80;
SELECT * FROM `siswa` WHERE tempat_lahir != 'SUBANG' AND nilai >= 80 AND alamat = 'CIJAMBE';
SELECT * FROM `siswa` WHERE nilai BETWEEN 60 AND 80;
SELECT * FROM `siswa` WHERE tanggal_lahir BETWEEN '2005-03-01' AND '2005-10-01';
SELECT * FROM `siswa` ORDER BY nilai DESC;
SELECT * FROM `siswa` ORDER BY nilai ASC;
SELECT * FROM `siswa` WHERE jenis_kelamin = 'L'ORDER BY nilai DESC;
SELECT * FROM `siswa` WHERE jenis_kelamin = 'L' AND tempat_lahir = 'SUBANG' ORDER BY nilai DESC;
SELECT * FROM `siswa` WHERE jenis_kelamin = 'P' AND nilai BETWEEN 50 AND 70 ORDER BY nilai DESC;
SELECT * FROM `siswa` WHERE nama LIKE 'A%';
SELECT * FROM `siswa` WHERE nama LIKE '%I';
SELECT * FROM `siswa` WHERE nama LIKE 'A%A';
SELECT * FROM `siswa` WHERE nama LIKE '%LI%';
SELECT tempat_lahir FROM `siswa` GROUP BY tempat_lahir;
SELECT tempat_lahir, COUNT(tempat_lahir) FROM `siswa` GROUP BY tempat_lahir;
SELECT tempat_lahir, COUNT(tempat_lahir) AS jumlah_orang FROM `siswa` GROUP BY tempat_lahir;
SELECT jenis_kelamin, MAX(nilai) AS nilai_tertinggi, MIN(nilai) AS nilai_terendah FROM `siswa` GROUP BY jenis_kelamin;
SELECT jenis_kelamin, MAX(nilai) AS nilai_tertinggi, MIN(nilai) AS nilai_terendah, AVG(nilai) AS nilai_rerata, SUM(nilai) AS nilai_total FROM `siswa` GROUP BY jenis_kelamin;
SELECT * FROM siswa WHERE YEAR(tanggal_lahir) = '2006';